title: MAS@B
description: Multi-Agent Systems Interst Group @ University of Birmingham
theme: minima # Options: jekyll-theme-minimal, minima

header_pages:
  - members.md
  - schedule.md
  - funding.md
